version: '3.9'
services:
  mysql-db:
    build:
      context: ./
      dockerfile: Dockerfile-mysql
    image: mysql-db:1.0
    container_name: mysql-db
    networks:
      - study-golang
    ports:
      - "23306:23306"
    volumes:
      - ../database/ddl:/docker-entrypoint-initdb.d
      - ../database/mysql_data:/var/lib/mysql
  app:
    depends_on:
      - mysql-db
    build:
      context: ./
      dockerfile: Dockerfile-golang
    image: app:1.0
    container_name: app
    networks:
      - study-golang
    ports:
      - "8080:8080"
    volumes:
      - ../app:/app
    env_file:
      - ../app/src/app.env

networks:
  study-golang:
    driver: bridge