version: '3.9'
services:
  mysql-db:
    build:
      context: ./
      dockerfile: Dockerfile-mysql
    image: mysql-db:1.0
    container_name: mysql-db
    networks:
      - study-golang
    ports:
      - "23306:23306"
    volumes:
      - ../database/ddl:/docker-entrypoint-initdb.d
      - ../mysql_data:/var/lib/mysql

  app:
    depends_on:
      - mysql-db
    build:
      context: ./
      dockerfile: Dockerfile-golang
    image: app:1.0
    container_name: app
    networks:
      - study-golang
    ports:
      - "18080:8080"
    volumes:
      - ../app:/app
      - ../database:/database
      - ../graphql:/graphql

  mysql-db-junit:
    depends_on:
      - mysql-db
    image: mysql-db:1.0
    container_name: mysql-db-junit
    command: --port 13306
    networks:
      - study-golang
    ports:
      - "13306:13306"
    volumes:
      - ../database/ddl/00_create_database.sql:/docker-entrypoint-initdb.d/00_create_database.sql
      - ../database/ddl/01_create_user.sql:/docker-entrypoint-initdb.d/01_create_user.sql
      - ../database/ddl/02_create_table.sql:/docker-entrypoint-initdb.d/02_create_table.sql

networks:
  study-golang:
    driver: bridge