FROM golang:1.19.1-alpine

RUN set -eux && \
    ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime

WORKDIR /app/src

RUN apk upgrade --update && \
    apk add build-base

ENV GOBIN=/usr/local/bin/
RUN go install github.com/cosmtrek/air@v1.40.4 && \
    go install golang.org/x/tools/cmd/goimports@v0.2.0 && \
    go install github.com/google/wire/cmd/wire@v0.5.0

CMD ["air", "-c", "/app/src/.air.toml"]