// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/seki-shinnosuke/study-golang/config"
	"github.com/seki-shinnosuke/study-golang/server/todo"
)

// Injectors from wire.go:

func InitializeService(configAPIServer *config.APIServer) *Server {
	todoService := todo.NewTodoService()
	server := NewServer(configAPIServer, todoService)
	return server
}
