// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"database/sql"
	"github.com/seki-shinnosuke/study-golang/config"
	todo2 "github.com/seki-shinnosuke/study-golang/controller/todo"
	"github.com/seki-shinnosuke/study-golang/usecase/todo"
)

// Injectors from wire.go:

func InitializeService(configAPIServer *config.APIServer, db *sql.DB) *Server {
	todoUsecase := todo.NewTodoUsecase(db)
	todoController := todo2.NewTodoController(todoUsecase)
	server := NewServer(configAPIServer, todoController)
	return server
}
